### ISSUE TITLE
Support of ARM architechture?

### ISSUE THREAD

**Issue by ProblemFactory** [akbaryahya/DockerGS#10]
I want to deploy this on my raspberry pi but it seems there is no ARM tags on dockerhub.

**Comment by akbaryahya** [comment]
yes so far there isn't for arm because i don't have raspberry for testing but maybe i can make it with buildx help but still don't know how to use it

**Comment by ProblemFactory** [comment]
Maybe you could just build the ARM version by selecting ARM versions of base images? If you could release that in dockerhub I can test it on my raspberry pi.

**Comment by 1995chen** [comment]
> yes so far there isn't for arm because i don't have raspberry for testing but maybe i can make it with buildx help but still don't know how to use it


I have a raspberry, if you are in mainland China, send an email to chenl2448365088@gmail.com and I can gift it to you

**Comment by AsrieltheGoat** [comment]
or use arm always free on oracle cloud

**Comment by akbaryahya** [comment]
I've tried using `qemu emulator` from arm64 it works fine, it's just that for real hardware tests I currently have `orange pi zero lts` unfortunately it doesn't work with arm/v7 because during the build process with github action I get an error `"Couldn't iterate through the jurisdiction policy files: unlimited"` so I'll close it for now until I find a better solution.
